export const CARDS = [
  { id: "galaxy_yongjunman", name: "갤럭시 용준맨", cardType: "monster", race: "갤럭시족", level: 7, atk: 0, def: 2300, effect: "이 카드가 특수 소환에 성공했을 경우, 제물로 바친 갤럭시족 몬스터들의 공격력 합계만큼 공격력을 얻는다. 이 카드는 직접 공격할 수 없다.", description: "은하의 힘을 품은 용준맨." },
  { id: "blue_eyes_yongjun", name: "푸른 눈의 이용준", cardType: "monster", race: "인간족", level: 5, atk: 600, def: 4500, effect: "이 카드가 소환에 성공했을 경우 상대 플레이어에게 이 카드의 공격력의 3배만큼 피해를 준다.", description: "푸른 눈을 가진 이용준." },
  { id: "dark_dragon_rider_yongjunman", name: "다크 드래곤 라이더 용준맨", cardType: "monster", race: "인간족", level: 8, atk: 1050, def: 2300, effect: "이 카드는 최소 1장, 최대 6장의 제물을 바쳐 특수 소환할 수 있다. 소환 시 공격력이 (원래 공격력 × 제물 수)만큼 증가한다.", description: "어둠의 용을 타고 전장을 누비는 기사." },
  { id: "little_kim_seungyu", name: "리틀 김승유", cardType: "monster", race: "인간족", level: 6, atk: 100, def: 3300, effect: "매 턴마다 눈물 스택을 1개 얻는다. 눈물 스택 1개당 공격력과 방어력이 각각 500 증가한다.", description: "눈물을 힘으로 바꾸는 소년." },
  { id: "coffee_geon", name: "커피를 마신 이건", cardType: "monster", race: "인간족", level: 4, atk: 1600, def: 5500, effect: "이 카드를 방어 표시로 소환했을 경우 즉시 파괴된다. 공격 표시 상태일 때 전투로는 절대 파괴되지 않는다.", description: "과도한 카페인으로 각성한 이건." },
  { id: "bone_geon", name: "뼈해장국먹는 이건", cardType: "monster", race: "인간족", level: 5, atk: 2900, def: 0, effect: "필드 위 모든 카드에 턴당 600 피해를 입힌다. 이 카드는 1000의 피해를 받는다.", description: "엄카로 뼈해장국 사먹은 이건." },
  { id: "paper", name: "이건의 딸휴지", cardType: "spell", level: 5, effect: "발동 시 상대 체력을 체력이 더 낮은 플레이어 쪽으로 설정한다. 게임당 한번만 발동 가능.", description: "건이가 버린 딸휴지!!" },
  { id: "goblin", name: "고블린 조련사 용준", cardType: "monster", race: "인간족", level: 6, atk: 0, def: 0, effect: "특수소환 성공 시 필드 위 카드 한장을 고블린으로 변환. 공격력 2배, 방어력 0. 고블린은 직접공격 불가.", description: "고블린과 SM." },
  { id: "beach", name: "해수욕장에 간 김승유", cardType: "monster", race: "인간족", level: 6, atk: 0, def: 1000, effect: "필드 인간족 수 × 1100 방어력 획득. 공격력 = 방어력 × 0.7", description: "아아아아!!! 아줌마!!!!" },
  { id: "ailen", name: "에일리언 이건", cardType: "monster", race: "에일리언족", level: 7, atk: 1200, def: 1200, effect: "특수소환 시 마법/함정 수 × 600 공격력 획득. 이후 사용된 마법 수 × 700 방어력 획득.", description: "헬다이버즈 할사람?" },
  { id: "blue", name: "태초의 푸른눈의 용준", cardType: "spell", level: 5, effect: "장착 카드는 전투로 파괴되지 않는다. 공격력 차이 1000 이상이면 상대 파괴. 중첩 가능.", description: "앙 기모띠" },
  { id: "shout", name: "용준의 깊은 결의", cardType: "spell", level: 4, effect: "아군 전체 방어력 +500. 게임 끝까지 유지.", description: "으아아아!!!!!!!!!!!" },
  { id: "masturbation", name: "자위 후의 김승유", cardType: "spell", level: 5, effect: "게임당 한번. 무작위 적 카드를 사용 불가로 만든다.", description: "자위 후 이성만 남은 김승유." },
  { id: "dick", name: "김연수의 4달 묵은 좆밥", cardType: "spell", level: 5, effect: "무작위 적 공격표시 카드 무력화. 막으면 3장 드로우.", description: "28일동안 씻지않아 응축된 좆밥." },
  { id: "spoon", name: "김연수가 한번 사용하고 버린 일회용 숟가락", cardType: "monster", race: "종족없음", level: 8, atk: 3333, def: 1500, effect: "효과없음", description: "엄청난 원한으로 영혼을 얻어 숟가락에 깃들었다." },
  { id: "friend", name: "김연수의 어릴시절 상상친구들", cardType: "monster", race: "인간족", level: 6, atk: 0, def: 2200, effect: "특수소환 시 덱의 김연수 관련 카드 × 400 공격력. 전투 파괴 시 덱 무작위 김연수 카드 효과 발동.", description: "유대감이 상상을 초월한다." },
  { id: "dairy", name: "김연수의 어린시절 일기장", cardType: "spell", level: 6, effect: "적 방어표시 카드 모두 공격표시 전환 + 공격력 절반. 300 이하면 파괴.", description: "그 누구에게도 보여주지않은 일기장." },
  { id: "turtle", name: "늙은 거북이의 후예 김연수", cardType: "monster", race: "인간족", level: 4, atk: 1500, def: 1000, effect: "효과없음", description: "전투를 피하지 않으며, 즐기는 특성." },
  { id: "tree", name: "성실한 나무꾼 김연수", cardType: "monster", race: "인간족", level: 8, atk: 4200, def: 1900, effect: "효과없음", description: "37년간의 나무꾼 생활로 인간을 초월한 완력." },
  { id: "cyberphunk", name: "2077년의 김연수", cardType: "monster", race: "인간족", level: 6, atk: 2500, def: 1400, effect: "방어표시 소환 시, 처음 공격받는 카드와의 공격력 차이만큼 공격력 획득.", description: "신체의 상당수가 로봇으로 개조되었다." },
  { id: "black", name: "어둠의 기사 임채환", cardType: "monster", race: "인간족", level: 6, atk: 1500, def: 2900, effect: "효과없음", description: "어둠의 힘을 사용하는 강인한 기사." },
  { id: "sword", name: "임채환의 검사의 길", cardType: "monster", race: "인간족", level: 6, atk: 2000, def: 2500, effect: "어떤 마법카드와도 감응하지 않는다. 검을 사용하는 카드 공격 시 공격력 절반.", description: "고된 훈련과 수행에 지친 임채환." },
  { id: "potato", name: "임채환의 봉인된 영혼", cardType: "spell", level: 4, effect: "상대 카드 하나를 지정해 공격력 절반으로 감소.", description: "한 마법사가 임채환의 영혼을 감자에 봉인." },
  { id: "hand", name: "임채환의 잘린손톱", cardType: "spell", level: 0, effect: "이 카드는 발동할 수 없다.", description: "임채환이 자르고 방치한 손톱." },
  { id: "MK", name: "임채환 MK II", cardType: "monster", race: "인간족", level: 8, atk: 3500, def: 2700, effect: "잘린손톱 3개를 제물로 소환 가능. 일반 소환 불가.", description: "키 188cm, 몸무게 72kg의 임채환 MK II." },
  { id: "repair", name: "수리공 임채환", cardType: "monster", race: "인간족", level: 5, atk: 2000, def: 1500, effect: "방어표시로 소환하면 방어력 +500.", description: "공학에 대한 지식이 뛰어나다." },
  { id: "grandfather", name: "노년기의 김승유", cardType: "monster", race: "인간족", level: 6, atk: 3300, def: 1800, effect: "모든 마법카드의 영향을 받지 않는다.", description: "수많은 전투에서 살아남은 노년의 김승유." },
  { id: "shoot", name: "임채환의 불꽃 슈팅", cardType: "spell", level: 4, effect: "인간족에게 방어력 -1000. 그 외 공격력 -1000.", description: "혼신의 힘을 다해 생명력까지 소모한 슈팅." },
  { id: "galaxy", name: "갤럭시 용준보이", cardType: "monster", race: "갤럭시족", level: 5, atk: 2000, def: 1500, effect: "마법 제외 공격 받을 시 동전 2개 던져 모두 앞면이면 무효화.", description: "산과 들을 뛰어다니며 자연과 교감." },
  { id: "hyupgek", name: "협객 임채환", cardType: "monster", race: "인간족", level: 5, atk: 2000, def: 2400, effect: "효과없음", description: "삼류 스승에게 무공을 배운 삼류 협객." },
  { id: "idol", name: "하츠네 채환", cardType: "monster", race: "인간족", level: 6, atk: 3000, def: 2400, effect: "효과없음", description: "하츠네 미쿠 코스프레를 한 임채환." },
  { id: "deep", name: "임채환의 깊은 신앙심", cardType: "spell", level: 7, effect: "아군 필드 카드 공격력 +700, 해로운 효과 제거. 아군 없으면 상대 HP -900.", description: "임채환의 깊은 신앙심에 천사가 반응!" },
  { id: "law", name: "로스쿨 재학생 임채환", cardType: "monster", race: "인간족", level: 3, atk: 1300, def: 1000, effect: "효과없음", description: "7수 끝에 로스쿨에 입학한 임채환." },
  { id: "bad", name: "악의 채환", cardType: "monster", race: "인간족", level: 5, atk: 2000, def: 2500, effect: "효과없음", description: "쁘띠허브의 악의 하인을 듣고 감명받은 임채환." },
  { id: "kill", name: "살육의 채환", cardType: "monster", race: "인간족", level: 5, atk: 2700, def: 1500, effect: "효과없음", description: "국가1급 현상수배범이 된 임채환." },
  { id: "judge", name: "연애재판 김연수", cardType: "monster", race: "인간족", level: 5, atk: 2300, def: 2000, effect: "효과없음", description: "연애재판을 듣고 마음을 사로잡힌 김연수." },
  { id: "idoll", name: "임채환, 아이돌 선언!", cardType: "monster", race: "인간족", level: 8, atk: 3700, def: 2500, effect: "효과없음", description: "아이돌이 된 임채환. 지하 라이브하우스에서 활동중." },
  { id: "turtley", name: "붉은 거북이의 후예 임채환", cardType: "monster", race: "인간족", level: 3, atk: 1000, def: 1200, effect: "효과없음", description: "호전적인 늙은 거북의 후예 임채환." },
  { id: "ox", name: "황소 임채환", cardType: "monster", race: "동물", level: 4, atk: 1800, def: 800, effect: "효과없음", description: "매우 큰 뿔을 가진 황소 임채환." },
  { id: "torii", name: "토리이 임채환", cardType: "spell", level: 5, effect: "장착 카드 공격력 +500. '임채환, 아이돌 선언!'이면 +1300, 방어력 -500.", description: "토리이를 지나가며 소망을 비는 임채환." },
  { id: "luck", name: "럭키 임채환", cardType: "monster", race: "인간족", level: 3, atk: 1000, def: 1000, effect: "효과없음", description: "운으로는 그 누구에게도 지지 않는다." },
  { id: "crystal", name: "크리스탈 임채환", cardType: "monster", race: "크리스탈족", level: 4, atk: 1500, def: 1200, effect: "효과없음", description: "크리스탈에 몸과 영혼을 빼앗긴 임채환." },
  { id: "desert", name: "사막의 파수꾼 임채환", cardType: "monster", race: "인간족", level: 3, atk: 1300, def: 1000, effect: "효과없음", description: "사막왕국의 장군, 왕국 부활을 기다리는 임채환." },
  { id: "love", name: "김연수의 순정", cardType: "spell", level: 4, effect: "게임당 한번. 체력 600 회복.", description: "김연수에게도 순정은 있었다." },
  { id: "sphagetti", name: "스파게티 김승유", cardType: "monster", race: "인간족", level: 4, atk: 1300, def: 1600, effect: "효과없음", description: "스파게티가 되어버린 김승유." },
  { id: "bunny", name: "바니걸 김연수", cardType: "monster", race: "인간족", level: 5, atk: 2500, def: 2000, effect: "마법카드 피해 2배. 인간족 공격 시 +500 공격력.", description: "바니걸이 되어버린 김연수." },
  { id: "wild", name: "야생의 김연수", cardType: "monster", race: "인간족", level: 8, atk: 3000, def: 3800, effect: "효과없음", description: "험난한 야생에서 길러진 김연수." },
  { id: "gal", name: "갤럭시 연수맨", cardType: "monster", race: "갤럭시족", level: 4, atk: 6974, def: 2000, effect: "공격표시로 소환 불가. 모든 공격 200만큼 감소.", description: "맞는 것을 즐기는 갤럭시 연수맨." },
  { id: "treeguy", name: "나무정령 김승유", cardType: "monster", race: "정령족", level: 4, atk: 2000, def: 1200, effect: "효과없음", description: "오랜 고목에 잡아먹혀 나무정령이 된 김승유." },
  { id: "pizza", name: "피자 배달부 김승유", cardType: "monster", race: "인간족", level: 6, atk: 2500, def: 3000, effect: "효과없음", description: "전역 후 생활비를 벌기위해 선택한 알바." },
  { id: "school", name: "학교에 가본 적이 없는 김승유", cardType: "monster", race: "인간족", level: 8, atk: 3500, def: 3000, effect: "직접 공격 시 2턴 후 500 추가 직접피해.", description: "러시아어로 노래를 부른다." },
  { id: "king", name: "왕의 근위병 김승유", cardType: "monster", race: "인간족", level: 4, atk: 9999, def: 2000, effect: "공격표시로 소환 불가. 방어표시로만 소환 가능.", description: "움직이지 않고 서 있어야하는 고된 근위병." },
  { id: "high", name: "높은 산의 김승유씨", cardType: "monster", race: "인간족", level: 7, atk: 2300, def: 3200, effect: "자신보다 공격력 높은 카드 공격 시 200 추가 데미지.", description: "잦은 등산으로 강인한 체력을 보유." },
  { id: "internet", name: "인터넷 망령 김승유", cardType: "monster", race: "인간족", level: 6, atk: 2700, def: 2500, effect: "효과없음", description: "오랜 인터넷 생활로 미소녀로 진화." },
  { id: "dog", name: "개승유", cardType: "monster", race: "동물", level: 5, atk: 1000, def: 2700, effect: "효과없음", description: "에드......워...드..오빠" },
  { id: "red_turtle", name: "붉은 거북의 후예 김승유", cardType: "monster", race: "인간족", level: 3, atk: 1200, def: 1000, effect: "효과없음", description: "단련을 통해 종족의 격을 뛰어넘으려 하는 김승유." },
  { id: "crystal2", name: "크리스탈 김승유", cardType: "monster", race: "크리스탈족", level: 5, atk: 2000, def: 2500, effect: "어떤 마법과도 감응하지 않는다.", description: "크리스탈의 힘을 흡수한 김승유." },
  { id: "crystal3", name: "크리스탈 킹 김승유", cardType: "monster", race: "크리스탈족", level: 7, atk: 2500, def: 3000, effect: "필드 위 크리스탈족 수 × 200 추가 공격력.", description: "종의 한계를 뛰어넘은 김승유." },
  { id: "galaxy3", name: "갤럭시 승유맨", cardType: "monster", race: "갤럭시족", level: 5, atk: 2700, def: 1700, effect: "방어표시 소환 시 방어력 -500.", description: "갤럭시족 전투민족의 후예." },
  { id: "bra", name: "브라끈 매지션 김승유", cardType: "monster", race: "인간족", level: 6, atk: 2500, def: 2800, effect: "효과없음", description: "여성 마법사들만 찾아다니며 브라를 요구하는 김승유." },
  { id: "blue2", name: "푸른눈의 김승유", cardType: "monster", race: "인간족", level: 4, atk: 1400, def: 1000, effect: "방어표시 소환 시 상대 필드의 카드 하나에 800 피해.", description: "푸른눈의 김승유." },
];

export const CARD_COLORS = {
  monster: { bg: '#1a1a2e', border: '#4a3f8c', header: '#2d2b55' },
  spell: { bg: '#0d2a1a', border: '#2d7a4a', header: '#1a4a2d' },
};

export const RACE_COLORS = {
  '인간족': '#c8a96e',
  '갤럭시족': '#7eb3ff',
  '에일리언족': '#7fffb3',
  '크리스탈족': '#d9b3ff',
  '정령족': '#ffcf7e',
  '동물': '#ff9e6e',
  '종족없음': '#aaaaaa',
};

export function getCardById(id) {
  return CARDS.find(c => c.id === id);
}
